Updated release process
Signed-off-by: Ali Abbas Jaffri <ali.abbasjaffri@live.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,44 +1,39 @@
 name: release
-
-# on:
-#   push:
-#     tags:
-#       - "v[0-9]+.[0-9]+.[0-9]+"
 on:
   push:
-    branches:
-      - main
+    tags:
+      - "v[0-9]+.[0-9]+.[0-9]+"
 
 jobs:
-  # check_version:
-  #   name: Check Cargo.toml version matches Git tag
-  #   runs-on: ubuntu-latest
-  #   outputs:
-  #     tag_version: ${{ steps.get_version.outputs.TAG_VERSION }}
-  #     cargo_version: ${{ steps.get_version.outputs.CARGO_VERSION }}
-  #   steps:
-  #     - uses: actions/checkout@v6
-  #     - name: Install toml-cli
-  #       run: cargo install toml-cli@0.2.3
-  #     - name: Get versions
-  #       id: get_version
-  #       run: |
-  #         TAG_VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
-  #         CARGO_VERSION=$(toml get Cargo.toml package.version | tr -d '"')
-  #         echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_OUTPUT
-  #         echo "CARGO_VERSION=$CARGO_VERSION" >> $GITHUB_OUTPUT
-  #     - name: Verify versions match
-  #       run: |
-  #         echo "Git tag version: ${{ steps.get_version.outputs.tag_version }}"
-  #         echo "Cargo.toml version: ${{ steps.get_version.outputs.cargo_version }}"
-  #         if [ "${{ steps.get_version.outputs.tag_version }}" != "${{ steps.get_version.outputs.cargo_version }}" ]; then
-  #           echo "Error: Git tag version (${{ steps.get_version.outputs.tag_version }}) does not match Cargo.toml version (${{ steps.get_version.outputs.cargo_version }})."
-  #           echo "Please run 'scripts/cargo_release.sh' to update the cargo version before generating tag."
-  #           exit 1
-  #         fi
+  check_version:
+    name: Check Cargo.toml version matches Git tag
+    runs-on: ubuntu-latest
+    outputs:
+      tag_version: ${{ steps.get_version.outputs.TAG_VERSION }}
+      cargo_version: ${{ steps.get_version.outputs.CARGO_VERSION }}
+    steps:
+      - uses: actions/checkout@v6
+      - name: Install toml-cli
+        run: cargo install toml-cli@0.2.3
+      - name: Get versions
+        id: get_version
+        run: |
+          TAG_VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
+          CARGO_VERSION=$(toml get Cargo.toml package.version | tr -d '"')
+          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_OUTPUT
+          echo "CARGO_VERSION=$CARGO_VERSION" >> $GITHUB_OUTPUT
+      - name: Verify versions match
+        run: |
+          echo "Git tag version: ${{ steps.get_version.outputs.tag_version }}"
+          echo "Cargo.toml version: ${{ steps.get_version.outputs.cargo_version }}"
+          if [ "${{ steps.get_version.outputs.tag_version }}" -le "${{ steps.get_version.outputs.cargo_version }}" ]; then
+            echo "Error: Git tag version (${{ steps.get_version.outputs.tag_version }}) does not match Cargo.toml version (${{ steps.get_version.outputs.cargo_version }})."
+            # echo "Please run 'scripts/cargo_release.sh' to update the cargo version before generating tag."
+            exit 1
+          fi
   build:
     name: Build multi-platform binaries
-    # needs: check_version
+    needs: check_version
     strategy:
       fail-fast: false
       matrix:
@@ -79,10 +74,9 @@ jobs:
             target/${{ matrix.platform.target }}/release/*.exe
             target/${{ matrix.platform.target }}/release/*.tar.gz
 
-  update-homebrew-and-krew:
-    name: Update Homebrew & Krew
+  release-github-krew-and-homebrew:
+    name: Create Release, Publish Crate, and Update Homebrew & Krew
     runs-on: ubuntu-latest
-    # needs: [update_version, build]
     needs: build
     permissions:
       contents: write
@@ -96,6 +90,19 @@ jobs:
       - name: List downloaded files
         run: ls -lahR dist/
 
+      - name: Create GitHub Release and Upload Assets
+        id: create_release
+        uses: softprops/action-gh-release@v2
+        with:
+          files: dist/**/*
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Update new version for kimspect in krew-index
+        uses: rajatjindal/krew-release-bot@v0.0.47
+        with:
+          krew_template_file: .krew/kimspect.yml
+
       - name: Update Homebrew Tap
         uses: ./.github/actions/update-homebrew
         with:
@@ -108,11 +115,6 @@ jobs:
           arm64_artifact_path: dist/aarch64-apple-darwin/kimspect-aarch64-apple-darwin
           tap_token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
 
-      - name: Update new version for kimspect in krew-index
-        uses: rajatjindal/krew-release-bot@v0.0.47
-        with:
-          krew_template_file: .krew/kimspect.yml
-
   # release-cargo:
   #   name: Release to cargo.io
   #   runs-on: ubuntu-latest
@@ -121,7 +123,7 @@ jobs:
   #     contents: write
   #   steps:
   #     - name: Checkout code
-  #       uses: actions/checkout@v6
+  #       uses: actions/checkout@v5
   #     - name: Publish to crates.io
   #       uses: actions-rs/cargo@v1
   #       with:
@@ -134,7 +136,7 @@ jobs:
     runs-on: ubuntu-latest
     permissions:
       contents: write
-    needs: [update-homebrew-and-krew]
+    needs: [release-github-krew-and-homebrew]
     steps:
       - name: Checkout code
         uses: actions/checkout@v6
@@ -169,7 +171,7 @@ jobs:
     concurrency:
       group: release-plz-${{ github.ref }}
       cancel-in-progress: false
-    needs: [update-homebrew-and-krew]
+    needs: [release-github-krew-and-homebrew]
     steps:
       - name: Checkout code
         uses: actions/checkout@v6
@@ -185,26 +187,3 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
-
-  release-github-artifacts:
-    name: Upload github artifacts to release
-    runs-on: ubuntu-latest
-    permissions:
-      contents: write
-    needs: [release-plz-release]
-    steps:
-      - name: Download build artifacts
-        uses: actions/download-artifact@v6
-        with:
-          path: dist/
-      - name: List downloaded files
-        run: ls -lahR dist/
-
-      - name: Create GitHub release and upload assets
-        id: create_release
-        uses: softprops/action-gh-release@v2
-        with:
-          files: dist/**/*
-          tag_name: ${{ needs.release-plz-release.outputs.release_tag }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
