Removing release-plz setup
Signed-off-by: Ali Abbas Jaffri <ali.abbasjaffri@live.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -5,8 +5,35 @@ on:
       - "v[0-9]+.[0-9]+.[0-9]+"
 
 jobs:
+  check_version:
+    name: Check Cargo.toml version matches Git tag
+    runs-on: ubuntu-latest
+    outputs:
+      tag_version: ${{ steps.get_version.outputs.TAG_VERSION }}
+      cargo_version: ${{ steps.get_version.outputs.CARGO_VERSION }}
+    steps:
+      - uses: actions/checkout@v6
+      - name: Install toml-cli
+        run: cargo install toml-cli@0.2.3
+      - name: Get versions
+        id: get_version
+        run: |
+          TAG_VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
+          CARGO_VERSION=$(toml get Cargo.toml package.version | tr -d '"')
+          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_OUTPUT
+          echo "CARGO_VERSION=$CARGO_VERSION" >> $GITHUB_OUTPUT
+      - name: Verify versions match
+        run: |
+          echo "Git tag version: ${{ steps.get_version.outputs.tag_version }}"
+          echo "Cargo.toml version: ${{ steps.get_version.outputs.cargo_version }}"
+          if [ "${{ steps.get_version.outputs.tag_version }}" != "${{ steps.get_version.outputs.cargo_version }}" ]; then
+            echo "Error: Git tag version (${{ steps.get_version.outputs.tag_version }}) does not match Cargo.toml version (${{ steps.get_version.outputs.cargo_version }})."
+            echo "Please run 'scripts/cargo_release.sh' to update the cargo version before generating tag."
+            exit 1
+          fi
   build:
     name: Build multi-platform binaries
+    needs: check_version
     strategy:
       fail-fast: false
       matrix:
@@ -47,8 +74,8 @@ jobs:
             target/${{ matrix.platform.target }}/release/*.exe
             target/${{ matrix.platform.target }}/release/*.tar.gz
 
-  release-github-krew-and-homebrew:
-    name: Create Release, Publish Crate, and Update Homebrew & Krew
+  release-github-homebrew-and-krew:
+    name: Create github release, update Homebrew & Krew
     runs-on: ubuntu-latest
     needs: build
     permissions:
@@ -74,11 +101,6 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Update new version for kimspect in krew-index
-        uses: rajatjindal/krew-release-bot@v0.0.47
-        with:
-          krew_template_file: .krew/kimspect.yml
-
       - name: Update Homebrew Tap
         uses: ./.github/actions/update-homebrew
         with:
@@ -90,3 +112,24 @@ jobs:
           amd64_artifact_path: dist/x86_64-apple-darwin/kimspect-x86_64-apple-darwin
           arm64_artifact_path: dist/aarch64-apple-darwin/kimspect-aarch64-apple-darwin
           tap_token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
+
+      - name: Update new version for kimspect in krew-index
+        uses: rajatjindal/krew-release-bot@v0.0.47
+        with:
+          krew_template_file: .krew/kimspec
+
+  release-cargo:
+    name: Release to cargo.io
+    runs-on: ubuntu-latest
+    needs: [release-github-homebrew-and-krew]
+    permissions:
+      contents: write
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v6
+      - name: Publish to crates.io
+        uses: actions-rs/cargo@v1
+        with:
+          command: publish
+        env:
+          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
